ctng_cpu_arch:
  - armv7l
ctng_vendor:
  - conda_cos7
ctng_target_platform:
  - linux-armv7l
cxx_compiler:       # [linux]
  - gcc_bootstrap   # [linux]
c_compiler_version:
  - 12
zip_keys:
  -
    - ctng_cpu_arch
    - ctng_vendor
    - ctng_target_platform
